[package]
name = "rustter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
askama = "0.13.0"
axum = "0.8.3"
bcrypt = "0.17.0"
r2d2 = "0.8.10"
r2d2_sqlite = "0.27.0"
serde = "1.0.219"
tokio = { version = "1.44.2", features = ["full"] }
tower-sessions = "0.14.0"
tower-sessions-r2d2-sqlite-store = { git = "https://github.com/untemi/tower-sessions-r2d2-sqlite-store", branch = "main" }

[dev-dependencies]
axum = { version = "0.8.3", features = ["macros"] }

[profile.dev.package.askama_derive]
opt-level = 3
