[package]
name = "carshift-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.97", default-features = false }
askama = "0.13.0"
axum = "0.8.3"
axum_typed_multipart = { version = "0.16.0", default-features = false }
bcrypt = "0.17.0"
chrono = "0.4.40"
colored = "3.0.0"
fancy-regex = "0.14.0"
iconify = "0.3.1"
lazy_static = "1.5.0"
mimalloc = "0.1.46"
paste = "1.0.15"
r2d2 = "0.8.10"
r2d2_sqlite = "0.27.0"
regex = "1.11.1"
serde = "1.0.219"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs"] }
tower-sessions = "0.14.0"
tower-sessions-r2d2-sqlite-store = { git = "https://github.com/untemi/tower-sessions-r2d2-sqlite-store", branch = "main" }
uuid = { version = "1.16.0", features = ["v4"] }
validator = { version = "0.20.0", features = ["derive"] }

[dev-dependencies]
axum = { version = "0.8.3", features = ["macros"] }

[profile.dev.build-override]
opt-level = 3

[profile.release]
strip = true
lto = "fat"
opt-level = 3
codegen-units = 1
