[package]
name = "cs-middlewares"
version = "0.1.0"
edition = "2024"

[dependencies]
cs-misc = { path = "../cs-misc" }
cs-database = { path = "../cs-database" }

axum = { workspace = true }
tower-sessions = { workspace = true }
