[package]
name = "cs-templ"
version = "0.1.0"
edition = "2024"

[dependencies]
cs-misc = { path = "../cs-misc" }
cs-database = { path = "../cs-database" }

askama = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }

iconify = "0.3.1"
